services:
  scrapper:
    build:
      context: .
      dockerfile: scrapper.Dockerfile
      tags:
        - scrapper:latest
    depends_on:
      - influx
    environment:
      - INFLUXDB_URL=http://influx:8086

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
      tags:
        - web:latest
    depends_on:
      - influx
    ports:
      - 8080:8081
    environment:
      - INFLUXDB_URL=http://influx:8086
    env_file:
      - path: .env


  influx:
    image: influxdb:2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=superuserus
      - DOCKER_INFLUXDB_INIT_ORG=jailedorg
      - DOCKER_INFLUXDB_INIT_BUCKET=main
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=xBqF4kCfBo80AF6Icflut7YN2-3AoDSDekJbxif38OVa8y4EuVaomUlXMZ6MPBX_XQAzdiPcViZr_2eMsK-KVw==
    ports:
      - 8086:8086
    volumes:
      - influx-config:/etc/influxdb
      - influx-store:/var/lib/influxdb

volumes:
  influx-store: {}
  influx-config: {}
