services:
  scrapper:
    build:
      context: .
      dockerfile: scrapper.Dockerfile
      tags:
        - scrapper:latest
    depends_on:
      - influx
    environment:
      - INFLUXDB_URL=http://influx:8086
    networks:
      influx_access: {}

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
      tags:
        - web:latest
    depends_on:
      - influx
      - scrapper
    environment:
      - INFLUXDB_URL=http://influx:8086
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 5
    networks:
      influx_access: {}
      front: {}

  certbot:
    build:
      context: compose/shared-volumes/certbot/.
      dockerfile: ../../../certbot.Dockerfile
    volumes:
      - nginx-certs:/var/certs
    environment:
      - DOMAIN_URL=corvaxmon.ip-ddns.com
      - DOMAIN_EMAIL=spamgate1945@gmail.com
    networks:
      certnet: { }

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./compose/shared-volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-certs:/etc/nginx
    depends_on:
      - web
      - certbot
    networks:
      certnet: { }
      front: { }


  influx:
    image: influxdb:2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=superuserus
      - DOCKER_INFLUXDB_INIT_ORG=jailedorg
      - DOCKER_INFLUXDB_INIT_BUCKET=main
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=xBqF4kCfBo80AF6Icflut7YN2-3AoDSDekJbxif38OVa8y4EuVaomUlXMZ6MPBX_XQAzdiPcViZr_2eMsK-KVw==
    ports:
      - 8086:8086
    volumes:
      - influx-config:/etc/influxdb
      - influx-store:/var/lib/influxdb
    networks:
      influx_access: { }

networks:
  certnet: {}
  front: {}
  influx_access: {}

volumes:
  influx-store: {}
  influx-config: {}
  nginx-certs: {}