apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: corvax-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corvax-monitor
  template:
    metadata:
      labels:
        app: corvax-monitor
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

